- hosts: localhost
  become: true
  pre_tasks:
    - name: refresh repositories
      shell: pkcon refresh
      register: refresh_output
      ignore_errors: true
    - name: update repositories
      shell: pkcon update -y
      register: update_output
      ignore_errors: true

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
    - include: tasks/config_zsh.yml
    - include: tasks/copy_assets.yml
