- name: Copy wallpaper
  become_user: root
  copy: 
    src: files/Starry-Nebula-108-4K.jpg 
    dest: /usr/share/wallpapers/Starry-Nebula-108/
    owner: orndorff
    group: orndorff
    mode: '0600'
    
- name: Copy theme
  become_user: orndorff
  copy: 
    src: files/Materia-Manjaro-Dark.tar.gz 
    dest: /home/orndorff/Downloads/Materia-Manjaro-Dark.tar.gz

- name: Extract theme
  become_user: orndorff
  unarchive: 
    src: /home/orndorff/Downloads/Materia-Manjaro-Dark.tar.gz 
    dest: /home/orndorff/Downloads
    remote_src: yes 

- name: Create theme directory
  become_user: orndorff
  file:
    path: /home/orndorff/.local/share/plasma/look-and-feel/
    state: directory
    mode: '0755'

- name: Move theme
  become_user: orndorff
  copy: 
    src: /home/orndorff/Downloads/Materia-Manjaro-Dark 
    dest: /home/orndorff/.local/share/plasma/look-and-feel
    remote_src: yes

- name: Copy color scheme
  become_user: orndorff
  copy: 
    src: files/color-schemes.tar.gz 
    dest: /home/orndorff/Downloads/color-schemes.tar.gz

- name: Extract color scheme
  become_user: orndorff
  unarchive:
    src: /home/orndorff/Downloads/color-schemes.tar.gz
    dest: /home/orndorff/Downloads
    remote_src: yes

- name: Create color scheme directory
  become_user: orndorff
  file:
    path: /home/orndorff/.local/share/color-schemes/
    state: directory
    mode: '0755'

- name: Move color scheme part one
  become_user: orndorff
  copy:
    src: /home/orndorff/Downloads/Adapta.colors 
    dest: /home/orndorff/.local/share/color-schemes
    remote_src: yes

- name: Move color scheme part two
  become_user: orndorff
  copy:
    src: /home/orndorff/Downloads/AdaptaNokto.colors
    dest: /home/orndorff/.local/share/color-schemes
    remote_src: yes

- name: Copy window decorations
  become_user: orndorff
  copy: 
    src: files/WindowsK10-0.6.2.tar.gz 
    dest: /home/orndorff/Downloads/WindowsK10-0.6.2.tar.gz

- name: Extract window decorations
  become_user: orndorff
  unarchive:
    src: /home/orndorff/Downloads/WindowsK10-0.6.2.tar.gz 
    dest: /home/orndorff/Downloads
    remote_src: yes

- name: Create window decorations directory
  become_user: orndorff
  file:
    path: /home/orndorff/.local/share/aurorae/themes/
    state: directory
    mode: '0755'

- name: Move window decorations part one
  become_user: orndorff
  copy:
    src: /home/orndorff/Downloads/K01
    dest: /home/orndorff/.local/share/aurorae/themes
    remote_src: yes

- name: Move window decorations part two
  become_user: orndorff
  copy:
    src: /home/orndorff/Downloads/K01-d
    dest: /home/orndorff/.local/share/aurorae/themes
    remote_src: yes

- name: Copy kconsole color theme
  become_user: orndorff
  copy: 
    src: files/konsole.tar.gz 
    dest: /home/orndorff/Downloads/konsole.tar.gz

- name: Extract kconsole color theme
  become_user: orndorff
  unarchive: 
    src: /home/orndorff/Downloads/konsole.tar.gz
    dest: /home/orndorff/Downloads
    remote_src: yes

- name: Move kconsole color theme
  become_user: orndorff
  copy: 
    src: /home/orndorff/Downloads/MateriaManjaro.colorscheme 
    dest: /home/orndorff/.local/share/konsole/
    remote_src: yes

- name: Copy Google font
  become_user: orndorff
  copy: 
    src: files/Montserrat.zip 
    dest: /home/orndorff/Downloads/Montserrat.zip

- name: Make Google font directory
  become_user: root
  file:
    path: /usr/share/fonts/googlefonts/
    state: directory
    mode: '0755'
  
- name: Unzip Google font to new directory
  become_user: root
  unarchive:
    src: /home/orndorff/Downloads/Montserrat.zip 
    dest: /usr/share/fonts/googlefonts
    remote_src: yes

- name: Create reference to new Google font directory
  shell: chmod -R --reference=/usr/share/fonts/opentype /usr/share/fonts/googlefonts

- name: Update font cache
  shell: fc-cache -fv
