- name: Copy wallpaper
  become_user: true
  copy: 
    src: files/Starry-Nebula-108-4K.jpg 
    dest: /usr/share/wallpapers/Starry_Nebula_108 
    
- name: Copy theme
  become_user: orndorff
  copy: 
    src: files/Materia-Manjaro-Dark.tar.gz 
    dest: /home/orndorff/Downloads/Materia-Manjaro-Dark.tar.gz

- name: Extract theme
  become_user: orndorff
  shell: tar -xvf /home/orndorff/Downloads/Materia-Manjaro-Dark.tar.gz

- name: Move theme
  become_user: orndorff
  shell: mv /home/orndorff/Downloads/Materia-Manjaro-Dark /home/orndorff/.local/share/plasma/look-and-feel

- name: Copy color scheme
  become_user: orndorff
  copy: 
    src: files/color-schemes.tar.gz 
    dest: /home/orndorff/Downloads/color-schemes.tar.gz

- name: Extract color scheme
  become_user: orndorff
  shell: tar -xvf /home/orndorff/Downloads/color-schemes.tar.gz

- name: Move color scheme
  become_user: orndorff
  shell: mv /home/orndorff/Downloads/Adapt*.colors /home/orndorff/.local/share/color-schemes

- name: Copy window decorations
  become_user: orndorff
  copy: 
    src: files/WindowsK10-0.6.2.tar.gz 
    dest: /home/orndorff/Downloads/WindowsK10-0.6.2.tar.gz

- name: Extract window decorations
  become_user: orndorff
  shell: tar -xvf /home/orndorff/Downloads/WindowsK10-0.6.2.tar.gz

- name: Move window decorations
  become_user: orndorff
  shell: mv /home/orndorff/Downloads/K01* /home/orndorff/.local/share/aurorae/themes

- name: Copy kconsole color theme
  become_user: orndorff
  copy: 
    src: files/konsole.tar.gz 
    dest: /home/orndorff/Downloads/konsole.tar.gz

- name: Extract kconsole color theme
  become_user: orndorff
  shell: tar -xvf /home/orndorff/Downloads/konsole.tar.gz

- name: Move kconsole color theme
  become_user: orndorff
  shell: mv /home/orndorff/Downloads/MateriaManjaro.colorscheme /home/orndorff/.local/share/konsole

- name: Copy Google font
  become_user: orndorff
  copy: 
    src: files/Montserrat.zip 
    dest: /home/orndorff/Downloads/Montserrat.zip

- name: Make Google font directory
  shell: mkdir /usr/share/fonts/googlefonts

- name: Unzip Google font to new directory
  shell: unzip -d /usr/share/fonts/googlefonts /home/orndorff/Downloads/Montserrat.zip

- name: Create reference to new Google font directory
  shell: chmod -R --reference=/usr/share/fonts/opentype /usr/share/fonts/googlefonts

- name: Update font cache
  shell: fc-cache -fv
